version: '3.8'

services:
  backend:
    build:
      context: .
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=db
    volumes:
      - .:/usr/src/app
    ports:
      - 8888:${TSPE_PORT}
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
volumes:
  back-notused:
  db-data: