version: '3.8'

services:
  backend:
    build:
      context: .
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=db
    volumes:
      - .:/usr/src/app
    ports:
      - 8888:${TSPE_PORT}
    depends_on:
      - db
      - ton-api-v4
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
  ton-api-v4:
    image: tonwhales/ton-api-v4:v38
    restart: always
    environment:
      - TON_CONFIG=${TON_CONFIG}
    expose:
      - 3000
  worker:
    build:
      context: .
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=db
      - TSPE_API_BASE_URL=${TSPE_API_BASE_URL}
    command: node dist/worker/index.js
    depends_on:
      - ton-api-v4
volumes:
  back-notused:
  db-data: