version: '3.8'

services:
  backend:
    build:
      context: .
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=db
    ports:
      - 8888:${TSPE_PORT}
    expose:
      - 8888
    depends_on:
      - db
      - ton-api-v4
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
  ton-api-v4:
    image: tonwhales/ton-api-v4:v38
    restart: always
    environment:
      - TON_CONFIG=${TON_CONFIG}
    ports:
      - 3000:3000
  worker:
    build:
      context: .
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=db
      - TSPE_API_BASE_URL=${TSPE_API_BASE_URL}
      - TSPE_STAKE_POOL_WALLET_ADDRESS=${TSPE_STAKE_POOL_WALLET_ADDRESS}
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
      - TSPE_STAKE_ACCEPTED_REGEXP=${TSPE_STAKE_ACCEPTED_REGEXP}
      - TSPE_WITHDRAW_COMPLETED_REGEXP=${TSPE_WITHDRAW_COMPLETED_REGEXP}
    command: node dist/worker/index.js
    depends_on:
      - ton-api-v4
      - redis
  redis:
    image: redis:alpine
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    env_file:
      - .env
    volumes:
    - redis-data:/data
    expose:
      - 6379
volumes:
  db-data:
  redis-data:
